version: 2
updates:
  # GHA
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - "*"

  # JS dependencies
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      dev-dependencies:
        dependency-type: development
      production-dependencies:
        dependency-type: production
