// User-extension sources (docs/extensions-plan.md "The loading pipeline",
// main half): scan `<configDir>/extensions/`, compile each single-file
// extension to plain JS (Node's own TypeScript type stripping — syntax only,
// no type checking), and keep the generated typing files fresh so the user's
// editor resolves `import type … from 'ved'` with no package setup. The
// renderer half (renderer/src/extension-host.ts) imports the compiled
// sources as blob modules. No `electron` import: unit-testable under vitest
// (the IPC glue lives in extension-service.ts).
import { type FSWatcher, watch } from 'node:fs';
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { stripTypeScriptTypes } from 'node:module';
import { basename, join } from 'node:path';
import { build } from 'esbuild';
// The user-facing API declaration: the shared source, written VERBATIM as
// ved.d.ts (extension-api.ts is types-only and self-contained for exactly
// this — the declaration users see cannot drift from the implementation).
import extensionApiSource from '../shared/extension-api.ts?raw';
import type { ExtensionSource } from '../shared/ipc';

/** Core command namespaces and shell families an extension id may not
 *  shadow: `history.ts` would otherwise register `history.*` commands over
 *  the built-ins. `init` is NOT reserved — init.ts is an ordinary extension
 *  whose commands live under `init.*`. */
export const RESERVED_EXTENSION_IDS: readonly string[] = [
  'appear',
  'history',
  'caret',
  'ruby',
  'editor',
  'file',
  'tab',
  'view',
  'search',
  'quickOpen',
  'vim',
  'ved',
];

/** The extension id of a single-file extension: its base name. */
export const extensionIdOf = (fileName: string): string => fileName.replace(/\.ts$/, '');

/** The single-file extension sources among `fileNames`, in load order:
 *  name-sorted (deterministic), `init.ts` LAST — so the user's own bindings
 *  win keybinding collisions against extension-shipped defaults. Generated
 *  and declaration files (`*.d.ts`) are not extensions. */
export const orderExtensionFiles = (fileNames: readonly string[]): string[] => {
  const sources = fileNames.filter((name) => name.endsWith('.ts') && !name.endsWith('.d.ts'));
  sources.sort();
  const init = sources.indexOf('init.ts');
  if (init !== -1) sources.push(...sources.splice(init, 1));
  return sources;
};

// Generated alongside ved.d.ts so ANY editor opened on the extensions dir
// typechecks user sources against it. verbatimModuleSyntax makes the checker
// enforce what the runtime does: the `ved` module exists only as types, so
// importing it must be `import type` (a value import fails to load).
const GENERATED_TSCONFIG = `${JSON.stringify(
  {
    '//': 'Generated by ved — do not edit (rewritten at every launch).',
    compilerOptions: {
      target: 'esnext',
      module: 'esnext',
      moduleResolution: 'bundler',
      lib: ['esnext', 'dom'],
      strict: true,
      noEmit: true,
      verbatimModuleSyntax: true,
      paths: { ved: ['./ved.d.ts'] },
    },
  },
  null,
  2,
)}\n`;

const GENERATED_DTS_HEADER = `// Generated by ved — do not edit (rewritten at every launch).
// The \`ved\` module's types; see docs/extensions-plan.md for the contract.
`;

/** Write `content` only when it differs — the user's editor may be watching
 *  the extensions dir, and an unchanged rewrite would still churn it. */
const writeIfChanged = async (path: string, content: string): Promise<void> => {
  const current = await readFile(path, 'utf-8').catch(() => null);
  if (current !== content) await writeFile(path, content, 'utf-8');
};

/** Compile one extension source to plain JS. Type STRIPPING only (Node's
 *  amaro, erasable syntax): `enum` &c. are load errors, and nothing
 *  type-checks here — the user's editor is the type checker. */
const compileExtension = (source: string, fileName: string): string => {
  if (typeof stripTypeScriptTypes !== 'function') {
    throw new Error('this runtime cannot strip TypeScript types (Node >= 22.13 required)');
  }
  return stripTypeScriptTypes(source, { mode: 'strip', sourceUrl: `ved-extension://${fileName}` });
};

/** One extension as found on disk, before compilation. A `project` is a
 *  directory with a `package.json` carrying a `ved` manifest field
 *  (`{ id?, entry, minAppVersion? }`); its whole module graph — relative
 *  imports and browser-safe npm dependencies — is bundled by esbuild into
 *  the one JS string the renderer imports. */
export type ScannedExtension =
  | { readonly kind: 'file'; readonly id: string; readonly fileName: string; readonly path: string }
  | {
      readonly kind: 'project';
      readonly id: string;
      readonly fileName: string;
      readonly dir: string;
      readonly entry: string;
      readonly minAppVersion: string | null;
    }
  | { readonly kind: 'invalid'; readonly id: string; readonly fileName: string; readonly error: string };

/** Is `version` (dotted numerics) at least `min`? Non-numeric segments
 *  compare as 0 — a deliberate shrug, not full semver. */
export const versionAtLeast = (version: string, min: string): boolean => {
  const a = version.split('.').map((s) => Number.parseInt(s, 10) || 0);
  const b = min.split('.').map((s) => Number.parseInt(s, 10) || 0);
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    const x = a[i] ?? 0;
    const y = b[i] ?? 0;
    if (x !== y) return x > y;
  }
  return true;
};

const scanProject = async (dir: string, fileName: string): Promise<ScannedExtension> => {
  const fallbackId = basename(fileName);
  try {
    const manifest = JSON.parse(await readFile(join(dir, 'package.json'), 'utf-8')) as {
      ved?: { id?: string; entry?: string; minAppVersion?: string };
    };
    const ved = manifest.ved;
    if (!ved || typeof ved.entry !== 'string') {
      return { kind: 'invalid', id: fallbackId, fileName, error: 'package.json has no `ved.entry` field' };
    }
    return {
      kind: 'project',
      id: typeof ved.id === 'string' && ved.id !== '' ? ved.id : fallbackId,
      fileName,
      dir,
      entry: ved.entry,
      minAppVersion: typeof ved.minAppVersion === 'string' ? ved.minAppVersion : null,
    };
  } catch (error) {
    return { kind: 'invalid', id: fallbackId, fileName, error: `unreadable package.json: ${String(error)}` };
  }
};

/** Everything under `<configDir>/extensions/` plus the `--dev-extension`
 *  working directories, in LOAD ORDER: name-sorted regular extensions, then
 *  the dev extensions, then `init.ts` last (the user's own bindings win). A
 *  duplicate id (or a reserved one) turns that entry `invalid`. */
export const scanExtensions = async (configDir: string, devPaths: readonly string[]): Promise<ScannedExtension[]> => {
  const dir = join(configDir, 'extensions');
  await mkdir(dir, { recursive: true });
  await writeIfChanged(join(dir, 'ved.d.ts'), GENERATED_DTS_HEADER + extensionApiSource);
  await writeIfChanged(join(dir, 'tsconfig.json'), GENERATED_TSCONFIG);

  const entries = await readdir(dir, { withFileTypes: true });
  const files = orderExtensionFiles(entries.filter((e) => e.isFile()).map((e) => e.name));
  const dirs = entries
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();

  const scanned: ScannedExtension[] = [];
  for (const name of dirs) scanned.push(await scanProject(join(dir, name), name));
  for (const fileName of files.filter((f) => f !== 'init.ts')) {
    scanned.push({ kind: 'file', id: extensionIdOf(fileName), fileName, path: join(dir, fileName) });
  }
  scanned.sort((a, b) => (a.fileName < b.fileName ? -1 : a.fileName > b.fileName ? 1 : 0));
  for (const devPath of devPaths) {
    scanned.push(
      devPath.endsWith('.ts')
        ? { kind: 'file', id: extensionIdOf(basename(devPath)), fileName: basename(devPath), path: devPath }
        : await scanProject(devPath, basename(devPath)),
    );
  }
  if (files.includes('init.ts')) {
    scanned.push({ kind: 'file', id: 'init', fileName: 'init.ts', path: join(dir, 'init.ts') });
  }

  const seen = new Set<string>();
  return scanned.map((s) => {
    if (s.kind !== 'invalid' && RESERVED_EXTENSION_IDS.includes(s.id)) {
      return {
        kind: 'invalid',
        id: s.id,
        fileName: s.fileName,
        error: `"${s.id}" is a reserved namespace — rename it`,
      };
    }
    if (seen.has(s.id)) {
      return { kind: 'invalid', id: s.id, fileName: s.fileName, error: `duplicate extension id "${s.id}"` };
    }
    seen.add(s.id);
    return s;
  });
};

/** Compile one scanned extension to its renderer-importable form. */
export const compileScanned = async (scanned: ScannedExtension, appVersion: string): Promise<ExtensionSource> => {
  const { id, fileName } = scanned;
  try {
    switch (scanned.kind) {
      case 'invalid':
        return { id, fileName, js: null, error: scanned.error };
      case 'file': {
        const source = await readFile(scanned.path, 'utf-8');
        return { id, fileName, js: compileExtension(source, fileName), error: null };
      }
      case 'project': {
        if (scanned.minAppVersion !== null && !versionAtLeast(appVersion, scanned.minAppVersion)) {
          return { id, fileName, js: null, error: `needs ved >= ${scanned.minAppVersion} (this is ${appVersion})` };
        }
        // `ved` is NOT marked external on purpose: type-only imports are
        // erased before resolution, so a resolution failure means a VALUE
        // import of the types-only module — better a clear bundle error here
        // than a cryptic blob-import failure in the renderer. Node built-ins
        // fail the same way: the renderer sandbox is the point.
        const result = await build({
          entryPoints: [join(scanned.dir, scanned.entry)],
          bundle: true,
          write: false,
          format: 'esm',
          platform: 'browser',
          target: 'es2022',
          absWorkingDir: scanned.dir,
          logLevel: 'silent',
        });
        return { id, fileName, js: result.outputFiles[0]?.text ?? '', error: null };
      }
    }
  } catch (error) {
    return { id, fileName, js: null, error: error instanceof Error ? error.message : String(error) };
  }
};

/**
 * The compiled user-extension sources, in load order. Creates the extensions
 * dir on first run and refreshes the generated typing files (`ved.d.ts`,
 * `tsconfig.json`). An extension that fails to load (reserved/duplicate id,
 * bad manifest, non-erasable syntax, bundle error) becomes an `error` entry —
 * reported to the user by the renderer, never fatal.
 */
export const loadExtensionSources = async (
  configDir: string,
  opts: { readonly devPaths?: readonly string[]; readonly appVersion?: string } = {},
): Promise<ExtensionSource[]> => {
  const scanned = await scanExtensions(configDir, opts.devPaths ?? []);
  return Promise.all(scanned.map((s) => compileScanned(s, opts.appVersion ?? '0.0.0')));
};

/**
 * Watch the extension sources and push recompiles (docs/extensions-plan.md
 * "Dev loop"): the extensions dir (top level — single-file extensions,
 * init.ts included) and each project/dev directory (recursive). Rebuilds are
 * debounced per extension id; a rebuild of a since-deleted file is dropped.
 * Returns the stop function.
 */
export const watchExtensions = (
  configDir: string,
  scanned: readonly ScannedExtension[],
  appVersion: string,
  onUpdate: (source: ExtensionSource) => void,
): (() => void) => {
  const dir = join(configDir, 'extensions');
  const timers = new Map<string, ReturnType<typeof setTimeout>>();
  const watchers: FSWatcher[] = [];

  const queue = (target: ScannedExtension): void => {
    clearTimeout(timers.get(target.id));
    timers.set(
      target.id,
      setTimeout(() => {
        timers.delete(target.id);
        void compileScanned(target, appVersion).then(onUpdate);
      }, 200),
    );
  };

  const tryWatch = (path: string, options: { recursive?: boolean }, listener: (fileName: string | null) => void) => {
    try {
      watchers.push(watch(path, options, (_event, fileName) => listener(fileName)));
    } catch (error) {
      console.warn(`ved: cannot watch ${path}: ${String(error)}`);
    }
  };

  // Top level: single-file extensions (generated files filtered out).
  tryWatch(dir, {}, (fileName) => {
    if (!fileName || !fileName.endsWith('.ts') || fileName.endsWith('.d.ts')) return;
    const target = scanned.find((s) => s.kind === 'file' && s.fileName === fileName);
    if (target) queue(target);
  });
  // Project and dev extensions: any change in their tree re-bundles.
  for (const s of scanned) {
    if (s.kind === 'project') tryWatch(s.dir, { recursive: true }, () => queue(s));
    else if (s.kind === 'file' && !s.path.startsWith(dir)) tryWatch(s.path, {}, () => queue(s));
  }

  return () => {
    for (const w of watchers) w.close();
    for (const t of timers.values()) clearTimeout(t);
  };
};

/** A single path segment (no separators, no `..`) — the only shape the
 *  storage channels accept for extension ids and file names. */
export const isSafeStorageSegment = (segment: string): boolean =>
  /^[\w.-]+$/.test(segment) && segment !== '.' && segment !== '..';

const storagePath = (configDir: string, id: string, file: string): string => {
  if (!isSafeStorageSegment(id) || !isSafeStorageSegment(file)) {
    throw new Error(`invalid storage path: ${id}/${file}`);
  }
  return join(configDir, 'storage', id, file);
};

/** Per-extension storage (`<configDir>/storage/<id>/`) — the fs capability
 *  the renderer sandbox deliberately lacks, scoped to one directory per
 *  extension id (the renderer host binds the id, so an extension cannot name
 *  another's). `null` = no such file. */
export const readExtensionStorage = async (configDir: string, id: string, file: string): Promise<string | null> =>
  readFile(storagePath(configDir, id, file), 'utf-8').catch((error) => {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  });

export const writeExtensionStorage = async (
  configDir: string,
  id: string,
  file: string,
  data: string,
): Promise<void> => {
  const path = storagePath(configDir, id, file);
  await mkdir(join(configDir, 'storage', id), { recursive: true });
  await writeFile(path, data, 'utf-8');
};
