// Vertical-Rows forward line move across a RUBY-SEAM column boundary.
//
// Regression for the "line move STUCK at a Vertical-Rows column boundary on a
// ruby seam" papercut (docs/architecture.md). When a forward line move lands on
// a column START whose offset is a text-less ruby seam, the DOM caret renders
// with END-of-PREVIOUS-column affinity, so the live DOM rect reports the PREVIOUS
// column's BOTTOM. `moveCaretByLine` then mis-indexes the caret one column back
// and the next forward step targets the column it is already in — no progress —
// so the no-progress guard reverts and the caret STICKS, never reaching the rest
// of the document. The fix resolves the seam with the AFTER-side model rect
// (`coordsAtPos(head, 1)`), which reports the column whose start is the seam.
//
// The fixture is a long ruby-heavy single paragraph (Rich, collapsed rubies) that
// wraps across ~6 columns; a column boundary falls on a ruby seam. Walking
// forward by line from offset 0, the caret must keep advancing past the stuck
// point. Without the fix the walk dies at offset 252 (3rd column); with it the
// walk reaches the last column (~701). We assert it passes 400 — unreachable
// while stuck — and that no forward step ever goes backward.
//
// VISIBLE window: moveCaretByLine defers via requestAnimationFrame, which hidden
// Electron windows throttle (the moves would silently no-op). See architecture.md.
import { clickWritingMode, fail, finish, launchVed, step } from './harness.ts';

const ved = await launchVed({ env: () => ({ VED_SMOKE_CLOSE_RESPONSE: 'discard', VED_SMOKE_HIDDEN: '' }) });
const { page } = ved;

// A ruby-heavy paragraph whose forward line walk, BEFORE the fix, sticks at
// offset 252 (a ruby-seam column start). Generated by the on-demand fuzz
// (test/e2e/fuzz-caret.ts) and frozen here for a deterministic regression.
const doc =
  '|名(な)ん|名(な)|語(ご)|漢(かん)|漢(かん)いう|名(な)ん|漢(かん)|名(な)|語(ご)|名(な)んん|名(な)|名(な)|漢(かん)亜あ亜|身体(からだ)|名(な)|漢(かん)|身体(からだ)|名(な)亜|語(ご)|漢(かん)|身体(からだ)|身体(からだ)んいう|漢(かん)|語(ご)あ亜|名(な)|語(ご)ん|漢(かん)あ亜あああ|名(な)ん|身体(からだ)あんいうああん|名(な)|身体(からだ)|漢(かん)ん|語(ご)ん亜|語(ご)亜|名(な)|漢(かん)あ亜|身体(からだ)いう亜あ|名(な)|漢(かん)|身体(からだ)|漢(かん)|身体(からだ)あ|名(な)|名(な)|名(な)|名(な)|語(ご)いう|漢(かん)あ|名(な)|語(ご)|漢(かん)あ|漢(かん)|漢(かん)|身体(からだ)|漢(かん)|漢(かん)|語(ご)|身体(からだ)亜|名(な)|語(ご)|語(ご)あ|名(な)|身体(からだ)亜|語(ご)|身体(からだ)|名(な)|身体(からだ)|身体(からだ)んん|語(ご)ん|語(ご)|語(ご)|語(ご)|身体(からだ)|語(ご)ん|名(な)|身体(からだ)あ|身体(からだ)|名(な)いう|名(な)|身体(からだ)|名(な)あ|語(ご)|漢(かん)|名(な)|名(な)|名(な)|語(ご)あ|漢(かん)|語(ご)ああ|漢(かん)|身体(からだ)あん|漢(かん)いういう|漢(かん)亜|身体(からだ)|漢(かん)|身体(からだ)|語(ご)|漢(かん)|身体(からだ)ん|漢(かん)|名(な)|漢(かん)|語(ご)|身体(からだ)|身体(からだ)亜|名(な)亜|身体(からだ)';

const caret = () => page.evaluate(() => (window as unknown as { __vedCaret(): number }).__vedCaret());

try {
  await clickWritingMode(page, 'Vertical Rows');
  await page.keyboard.down('Control'); // Rich — collapsed rubies, where seams bite
  await page.keyboard.press('Digit4');
  await page.keyboard.up('Control');
  await page.click('#editor-content');
  await page.evaluate(() => getSelection()!.selectAllChildren(document.getElementById('editor-content')!));
  await page.keyboard.press('Backspace');
  await page.waitForTimeout(60);
  await page.keyboard.insertText(doc);
  await page.waitForTimeout(300);

  await page.evaluate(() => (window as unknown as { __vedSetCaret(o: number): void }).__vedSetCaret(0));
  await page.waitForTimeout(80);

  // Press, then POLL until the move settles (the visible window's rAF lags under
  // load); a settled no-op (no change within the cap) ends the walk.
  const pressLine = async (): Promise<boolean> => {
    const before = await caret();
    await page.keyboard.press('ArrowLeft');
    for (let k = 0; k < 200; k++) {
      await page.waitForTimeout(16);
      if ((await caret()) !== before) return true;
    }
    return false;
  };

  const trace = [await caret()];
  let reversed = -1;
  let max = trace[0]!;
  for (let s = 0; s < 30; s++) {
    const before = await caret();
    const moved = await pressLine();
    const o = await caret();
    trace.push(o);
    if (o < before) reversed = s; // a forward step must never decrease the offset
    max = Math.max(max, o);
    if (!moved) break;
  }

  console.log(`trace: ${trace.join(' -> ')}`);
  if (reversed >= 0) {
    fail(`forward line move #${reversed} went BACKWARD: ${trace[reversed]} -> ${trace[reversed + 1]}`);
  } else if (max < 400) {
    fail(
      `forward line walk STUCK at offset ${max} (doc len ${doc.length}) — never crossed the ruby-seam column boundary (expected to pass 400)`,
    );
  } else {
    step(`forward line move crosses the ruby-seam column boundary (reached offset ${max}/${doc.length})`);
  }
} catch (e) {
  fail(e instanceof Error ? e.message : String(e));
} finally {
  await ved.close();
}

finish('vrows-ruby-seam-line-move e2e');
