// Generate the API reference (docs/api/) for ved's typed surfaces.
//
//   node scripts/gen-api-docs.ts            # write docs/api/**/*.md
//   node scripts/gen-api-docs.ts --check    # fail if the docs are stale
//   node scripts/gen-api-docs.ts --open     # also render HTML (out/api-docs/)
//                                           # and open it in the browser
//
// One module per public seam: `ved` (the user-extension API — the same
// source that is written verbatim to `<configDir>/extensions/ved.d.ts`, so
// the reference cannot drift from what an extension author imports),
// `editor` (@ved/editor's exports entry, the seam @ved/vim builds on),
// `vim` (@ved/vim's exports entry), and `ipc` (the main/preload/renderer
// contract). Extraction is ox-content's OXC pipeline (no TypeScript
// compiler API — it keeps working across tsc major versions).

import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, unlinkSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { extractDocsFromEntryPoints, generateDocsMarkdown, parseAndRender } from '@ox-content/napi';

const REPO_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT_DIR = join(REPO_ROOT, 'docs/api');

// `pkg` is the entry's workspace package directory — the segment the
// generator's source links drop (see the patch below). `desc` annotates the
// root index's module list.
const MODULES = [
  {
    name: 'ved',
    entry: 'desktop/src/shared/extension-api.ts',
    pkg: 'desktop',
    desc: 'the `ved` module a USER EXTENSION imports (written to `ved.d.ts` verbatim)',
  },
  {
    name: 'editor',
    entry: 'editor/src/index.ts',
    pkg: 'editor',
    desc: "@ved/editor's public surface — props, commands, and the extension seam",
  },
  {
    name: 'vim',
    entry: 'vim/src/index.ts',
    pkg: 'vim',
    desc: "@ved/vim's public surface — the extension factory, keymap config, binding catalog",
  },
  {
    name: 'ipc',
    entry: 'desktop/src/shared/ipc.ts',
    pkg: 'desktop',
    desc: 'the main/preload/renderer contract behind `window.ved`',
  },
] as const;

// The OXC extraction follows every re-export, including non-TS ones it
// cannot parse (@ved/editor re-exports its stylesheet). Such an entry is
// extracted through a SHADOW copy with those lines dropped; the styles
// export just goes undocumented.
const shadowOf = (entry: string): string | null => {
  const source = readFileSync(join(REPO_ROOT, entry), 'utf8');
  const kept = source.split('\n').filter((line) => !/from\s+'[^']+\.(scss|css)'/.test(line));
  if (kept.length === source.split('\n').length) return null;
  const shadow = join(dirname(entry), '.api-docs-entry.ts');
  writeFileSync(join(REPO_ROOT, shadow), kept.join('\n'));
  return shadow;
};

const shadows = new Map(MODULES.map((m) => [m.name, shadowOf(m.entry)]));
let modules: ReturnType<typeof extractDocsFromEntryPoints>;
try {
  modules = extractDocsFromEntryPoints(
    MODULES.map((m) => ({ path: shadows.get(m.name) ?? m.entry, name: m.name })),
    { root: REPO_ROOT },
  );
} finally {
  for (const shadow of shadows.values()) {
    if (shadow) unlinkSync(join(REPO_ROOT, shadow));
  }
}

for (const m of modules) {
  for (const d of m.diagnostics) {
    console.error(`${d.code} ${d.entrypoint} ${d.exportName}: ${d.message}`);
  }
}
if (modules.some((m) => m.diagnostics.length > 0)) process.exit(1);

// generateDocsMarkdown takes entry tags as ordered pairs; extraction hands
// them back as a record. A shadowed module's source link points back at the
// real entry.
const pages = generateDocsMarkdown(
  modules.map((m) => {
    const declared = MODULES.find((d) => d.name === m.name);
    if (!declared) throw new Error(`extraction returned unknown module ${m.name}`);
    return {
      file: m.file,
      description: m.description,
      sourcePath: shadows.get(m.name) ? join(REPO_ROOT, declared.entry) : m.sourcePath,
      examples: m.examples,
      tags: m.tags,
      entries: m.entries.map((e) => ({
        ...e,
        tags: e.tags ? Object.entries(e.tags).map(([tag, value]) => ({ tag, value })) : undefined,
      })),
    };
  }),
  {
    // The generator appends `/blob/main/<file relative to its PACKAGE>`.
    githubUrl: 'https://github.com/toyboot4e/ved',
    pathStrategy: 'typedoc',
    renderStyle: 'markdown',
  },
);

const banner = [
  '<!-- GENERATED by scripts/gen-api-docs.ts — do not edit by hand.',
  '     Run `pnpm run api-docs` (or `just doc`) to refresh. -->',
  '',
].join('\n');

// Patch two ox-content@2.76 rendering quirks:
//   - source links relativize the file path to the nearest package, dropping
//     the monorepo segment (`blob/main/src/…` for a file under `desktop/`) —
//     every page belongs to one module, so its links get that module's
//     package dir back (the root index links no sources);
//   - a negative numeric literal type prints as `literal` (`1 | -1` in the
//     source renders `1 | literal`).
const patch = (path: string, content: string): string => {
  const owner = MODULES.find((m) => path.startsWith(`${m.name}/`));
  let out = owner ? content.replaceAll('/blob/main/src/', `/blob/main/${owner.pkg}/src/`) : content;
  if (path === 'index.md') {
    // The root module list renders bare names; annotate each with its role.
    for (const m of MODULES) {
      out = out.replace(`- [${m.name}](./${m.name}/index.md)`, `- [${m.name}](./${m.name}/index.md) — ${m.desc}`);
    }
  }
  return out.replaceAll('1 | literal', '1 | -1');
};

const files = new Map<string, string>(
  Object.entries(pages).map(([path, content]) => [path, banner + patch(path, content)]),
);

if (process.argv.includes('--check')) {
  const onDisk = existsSync(OUT_DIR)
    ? readdirSync(OUT_DIR, { recursive: true, withFileTypes: true })
        .filter((e) => e.isFile())
        .map((e) => join(e.parentPath.slice(OUT_DIR.length + 1), e.name))
    : [];
  const stale =
    onDisk.length !== files.size ||
    [...files].some(([path, content]) => {
      const p = join(OUT_DIR, path);
      return !existsSync(p) || readFileSync(p, 'utf8') !== content;
    });
  if (stale) {
    console.error('API docs are stale — run `pnpm run api-docs`');
    process.exit(1);
  }
  console.log('API docs are up to date');
} else {
  rmSync(OUT_DIR, { recursive: true, force: true });
  for (const [path, content] of files) {
    mkdirSync(dirname(join(OUT_DIR, path)), { recursive: true });
    writeFileSync(join(OUT_DIR, path), content);
  }
  console.log(`wrote ${files.size} pages for ${modules.length} modules`);

  if (process.argv.includes('--open')) {
    const htmlDir = join(REPO_ROOT, 'out/api-docs');
    rmSync(htmlDir, { recursive: true, force: true });
    for (const [path, content] of files) {
      // Relative page links target the .md siblings; the HTML tree mirrors it.
      const md = content.replace(/\((\.[^)#]*)\.md(#[^)]*)?\)/g, (_m, p, h) => `(${p}.html${h ?? ''})`);
      const { html, errors } = parseAndRender(md, { gfm: true });
      for (const e of errors) console.error(`${path}: ${e}`);
      const title = content.match(/^# (.+)$/m)?.[1] ?? path;
      const htmlPath = join(htmlDir, path.replace(/\.md$/, '.html'));
      mkdirSync(dirname(htmlPath), { recursive: true });
      writeFileSync(htmlPath, htmlPage(title, html));
    }
    const index = join(htmlDir, 'index.html');
    console.log(`rendered HTML → ${index}`);
    const opener = process.platform === 'darwin' ? 'open' : 'xdg-open';
    spawn(opener, [index], { detached: true, stdio: 'ignore' }).unref();
  }
}

function htmlPage(title: string, body: string): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title} — ved API</title>
<style>
  body { max-width: 52rem; margin: 2rem auto; padding: 0 1rem; font-family: system-ui, sans-serif; line-height: 1.6; }
  code { background: #f4f4f4; padding: 0.1em 0.3em; border-radius: 3px; font-size: 0.9em; }
  pre { background: #f4f4f4; padding: 0.8em; border-radius: 6px; overflow-x: auto; }
  pre code { background: none; padding: 0; }
  table { border-collapse: collapse; }
  th, td { border: 1px solid #ccc; padding: 0.3em 0.6em; text-align: left; }
  a { color: #0857a6; }
  @media (prefers-color-scheme: dark) {
    body { background: #1b1b1d; color: #ddd; }
    code, pre { background: #2a2a2d; }
    th, td { border-color: #444; }
    a { color: #7ab7ff; }
  }
</style>
</head>
<body>
${body}
</body>
</html>
`;
}
