// Generate the API reference (docs/api/) for ved's typed surfaces.
//
//   node scripts/gen-api-docs.ts            # write docs/api/**/*.md
//   node scripts/gen-api-docs.ts --check    # fail if the docs are stale
//   node scripts/gen-api-docs.ts --open     # also render HTML (out/api-docs/)
//                                           # and open it in the browser
//
// One module per public seam: `ved` (the user-extension API — the same
// source that is written verbatim to `<configDir>/extensions/ved.d.ts`, so
// the reference cannot drift from what an extension author imports),
// `editor` (@ved/editor's exports entry, the seam @ved/vim builds on),
// `vim` (@ved/vim's exports entry), and `ipc` (the main/preload/renderer
// contract). Extraction is ox-content's OXC pipeline (no TypeScript
// compiler API — it keeps working across tsc major versions).

import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, unlinkSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  externalizeSsgAssets,
  extractDocsFromEntryPoints,
  generateDocsMarkdown,
  generateDocsNavMetadataFromDocs,
  generateSsgHtml,
  transform,
} from '@ox-content/napi';

const REPO_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT_DIR = join(REPO_ROOT, 'docs/api');

// `pkg` is the entry's workspace package directory — the segment the
// generator's source links drop (see the patch below). Each entry file's
// leading JSDoc block is the module's description (the root index quotes it).
const MODULES = [
  { name: 'ved', entry: 'desktop/src/shared/extension-api.ts', pkg: 'desktop' },
  { name: 'editor', entry: 'editor/src/index.ts', pkg: 'editor' },
  { name: 'vim', entry: 'vim/src/index.ts', pkg: 'vim' },
  { name: 'ipc', entry: 'desktop/src/shared/ipc.ts', pkg: 'desktop' },
] as const;

// The OXC extraction follows every re-export, including non-TS ones it
// cannot parse (@ved/editor re-exports its stylesheet). Such an entry is
// extracted through a SHADOW copy with those lines dropped; the styles
// export just goes undocumented.
const shadowOf = (entry: string): string | null => {
  const source = readFileSync(join(REPO_ROOT, entry), 'utf8');
  const kept = source.split('\n').filter((line) => !/from\s+'[^']+\.(scss|css)'/.test(line));
  if (kept.length === source.split('\n').length) return null;
  const shadow = join(dirname(entry), '.api-docs-entry.ts');
  writeFileSync(join(REPO_ROOT, shadow), kept.join('\n'));
  return shadow;
};

const shadows = new Map(MODULES.map((m) => [m.name, shadowOf(m.entry)]));
let modules: ReturnType<typeof extractDocsFromEntryPoints>;
try {
  modules = extractDocsFromEntryPoints(
    MODULES.map((m) => ({ path: shadows.get(m.name) ?? m.entry, name: m.name })),
    { root: REPO_ROOT },
  );
} finally {
  for (const shadow of shadows.values()) {
    if (shadow) unlinkSync(join(REPO_ROOT, shadow));
  }
}

for (const m of modules) {
  for (const d of m.diagnostics) {
    console.error(`${d.code} ${d.entrypoint} ${d.exportName}: ${d.message}`);
  }
}
if (modules.some((m) => m.diagnostics.length > 0)) process.exit(1);

// generateDocsMarkdown takes entry tags as ordered pairs; extraction hands
// them back as a record. A shadowed module's source link points back at the
// real entry.
const docs = modules.map((m) => {
  const declared = MODULES.find((d) => d.name === m.name);
  if (!declared) throw new Error(`extraction returned unknown module ${m.name}`);
  return {
    file: m.file,
    description: m.description,
    sourcePath: shadows.get(m.name) ? join(REPO_ROOT, declared.entry) : m.sourcePath,
    examples: m.examples,
    tags: m.tags,
    entries: m.entries.map((e) => ({
      ...e,
      tags: e.tags ? Object.entries(e.tags).map(([tag, value]) => ({ tag, value })) : undefined,
    })),
  };
});

const MD_OPTIONS = {
  // The generator appends `/blob/main/<file relative to its PACKAGE>`.
  githubUrl: 'https://github.com/toyboot4e/ved',
  pathStrategy: 'typedoc',
} as const;

const pages = generateDocsMarkdown(docs, { ...MD_OPTIONS, renderStyle: 'markdown' });

const banner = [
  '<!-- GENERATED by scripts/gen-api-docs.ts — do not edit by hand.',
  '     Run `pnpm run api-docs` (or `just doc`) to refresh. -->',
  '',
].join('\n');

// Patch two ox-content@2.76 rendering quirks:
//   - source links relativize the file path to the nearest package, dropping
//     the monorepo segment (`blob/main/src/…` for a file under `desktop/`) —
//     every page belongs to one module, so its links get that module's
//     package dir back (the root index links no sources);
//   - a negative numeric literal type prints as `literal` (`1 | -1` in the
//     source renders `1 | literal`).
const patch = (path: string, content: string): string => {
  const owner = MODULES.find((m) => path.startsWith(`${m.name}/`));
  const out = owner ? content.replaceAll('/blob/main/src/', `/blob/main/${owner.pkg}/src/`) : content;
  return out.replaceAll('1 | literal', '1 | -1');
};

const files = new Map<string, string>(
  Object.entries(pages).map(([path, content]) => [path, banner + patch(path, content)]),
);

if (process.argv.includes('--check')) {
  const onDisk = existsSync(OUT_DIR)
    ? readdirSync(OUT_DIR, { recursive: true, withFileTypes: true })
        .filter((e) => e.isFile())
        .map((e) => join(e.parentPath.slice(OUT_DIR.length + 1), e.name))
    : [];
  const stale =
    onDisk.length !== files.size ||
    [...files].some(([path, content]) => {
      const p = join(OUT_DIR, path);
      return !existsSync(p) || readFileSync(p, 'utf8') !== content;
    });
  if (stale) {
    console.error('API docs are stale — run `pnpm run api-docs`');
    process.exit(1);
  }
  console.log('API docs are up to date');
} else {
  rmSync(OUT_DIR, { recursive: true, force: true });
  for (const [path, content] of files) {
    mkdirSync(dirname(join(OUT_DIR, path)), { recursive: true });
    writeFileSync(join(OUT_DIR, path), content);
  }
  console.log(`wrote ${files.size} pages for ${modules.length} modules`);

  if (process.argv.includes('--open')) {
    const htmlDir = join(REPO_ROOT, 'out/api-docs');
    rmSync(htmlDir, { recursive: true, force: true });

    // The HTML build re-renders the pages in `renderStyle: 'html'` — the
    // structured `ox-api-*` markup the SSG theme styles (signature blocks,
    // member cards) — while docs/api keeps the plain-Markdown style.
    const htmlPages = generateDocsMarkdown(docs, { ...MD_OPTIONS, renderStyle: 'html' });

    // Sidebar: one nav item tree per module (module overview + one node per
    // kind group), plus the root index. Hrefs are made page-relative below —
    // the site is browsed over file://, so nothing may be root-absolute.
    const navMeta = generateDocsNavMetadataFromDocs(docs, { pathStrategy: 'typedoc', basePath: '' });
    type NavItem = { title: string; path: string; href: string; children?: NavItem[] };
    const toItem = (n: (typeof navMeta)[number], self: string): NavItem => ({
      title: n.title,
      path: self,
      href: self,
      children: n.children?.map((c) => toItem(c, c.children ? `${c.path.slice(1)}` : `${c.path.slice(1)}.html`)),
    });
    const navGroups = [
      { title: 'ved API', items: [{ title: 'Modules', path: 'index.html', href: 'index.html' }] },
      ...navMeta.map((m) => ({ title: m.title, items: [toItem(m, `${m.path.slice(1)}/index.html`)] })),
    ];

    // A kind node (`editor/functions`) has no page of its own — point it at
    // its module index so the theme still renders it as a link.
    const fixKindHrefs = (items: NavItem[], moduleIndex: string): void => {
      for (const it of items) {
        if (it.children) {
          if (!it.href.endsWith('.html')) {
            it.href = moduleIndex;
            it.path = moduleIndex;
          }
          fixKindHrefs(it.children, moduleIndex);
        }
      }
    };
    for (const g of navGroups.slice(1)) fixKindHrefs(g.items, `${g.title}/index.html`);

    const rendered: { outputPath: string; inputPath: string; html: string }[] = [];
    for (const [path, raw] of Object.entries(htmlPages)) {
      const content = patch(path, raw);
      // Relative page links target the .md siblings; the HTML tree mirrors
      // it. `renderStyle: 'html'` emits both Markdown links and raw anchors.
      const md = content
        .replace(/\((\.[^)#]*)\.md(#[^)]*)?\)/g, (_m, p, h) => `(${p}.html${h ?? ''})`)
        .replace(/href="(\.[^"#]*)\.md(#[^"]*)?"/g, (_m, p, h) => `href="${p}.html${h ?? ''}"`);
      const { html, toc, errors } = transform(md, { gfm: true });
      for (const e of errors) console.error(`${path}: ${e}`);
      const title = content.match(/^# (.+)$/m)?.[1] ?? path;
      const prefix = '../'.repeat(path.split('/').length - 1);
      const relativize = (items: NavItem[]): NavItem[] =>
        items.map((it) => ({ ...it, href: prefix + it.path, children: it.children && relativize(it.children) }));
      const page = generateSsgHtml(
        { title, content: html, toc, path: `/${path.replace(/\.md$/, '')}` },
        navGroups.map((g) => ({ title: g.title, items: relativize(g.items) })),
        { siteName: 'ved API', base: '/', theme: { header: { logo: '/logo.png' } } },
      );
      // The theme's own chrome (home link, logo, asset urls) is root-absolute;
      // rebase it onto this page's relative prefix for file:// browsing.
      const rebased = page.replace(
        /(href|src)="\/([^"]*)"/g,
        (_m, attr, p) => `${attr}="${prefix}${p || 'index.html'}"`,
      );
      rendered.push({ inputPath: path, outputPath: join(htmlDir, path.replace(/\.md$/, '.html')), html: rebased });
    }

    // Pull the theme's shared CSS/JS out of every page into one assets/ dir
    // (the pages arrive with them inlined — ~60 KB × 87 pages).
    const { pages: finalPages, assets } = externalizeSsgAssets(rendered, htmlDir, '/');
    for (const a of assets) {
      mkdirSync(dirname(a.outputPath), { recursive: true });
      writeFileSync(a.outputPath, a.content);
    }
    for (const p of finalPages) {
      const prefix = '../'.repeat(p.inputPath.split('/').length - 1);
      mkdirSync(dirname(p.outputPath), { recursive: true });
      writeFileSync(p.outputPath, p.html.replace(/(href|src)="\/assets\//g, `$1="${prefix}assets/`));
    }

    writeFileSync(join(htmlDir, 'logo.png'), readFileSync(join(REPO_ROOT, 'desktop/resources/icon.png')));

    const index = join(htmlDir, 'index.html');
    console.log(`rendered HTML → ${index}`);
    const opener = process.platform === 'darwin' ? 'open' : 'xdg-open';
    spawn(opener, [index], { detached: true, stdio: 'ignore' }).unref();
  }
}
