// Generate the API reference (docs/api/) for ved's typed surfaces.
//
//   node scripts/gen-api-docs.ts            # write docs/api/**/*.md
//   node scripts/gen-api-docs.ts --check    # fail if the docs are stale
//
// One module per public seam: `ved` (the user-extension API — the same
// source that is written verbatim to `<configDir>/extensions/ved.d.ts`, so
// the reference cannot drift from what an extension author imports),
// `editor` (@ved/editor's exports entry, the seam @ved/vim builds on),
// `vim` (@ved/vim's exports entry), and `ipc` (the main/preload/renderer
// contract). Extraction is ox-content's OXC pipeline (no TypeScript
// compiler API — it keeps working across tsc major versions).

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, unlinkSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { extractDocsFromEntryPoints, generateDocsMarkdown } from '@ox-content/napi';

const REPO_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT_DIR = join(REPO_ROOT, 'docs/api');

// `pkg` is the entry's workspace package directory — the segment the
// generator's source links drop (see the patch below). `desc` annotates the
// root index's module list.
const MODULES = [
  {
    name: 'ved',
    entry: 'desktop/src/shared/extension-api.ts',
    pkg: 'desktop',
    desc: 'the `ved` module a USER EXTENSION imports (written to `ved.d.ts` verbatim)',
  },
  {
    name: 'editor',
    entry: 'editor/src/index.ts',
    pkg: 'editor',
    desc: "@ved/editor's public surface — props, commands, and the extension seam",
  },
  {
    name: 'vim',
    entry: 'vim/src/index.ts',
    pkg: 'vim',
    desc: "@ved/vim's public surface — the extension factory, keymap config, binding catalog",
  },
  {
    name: 'ipc',
    entry: 'desktop/src/shared/ipc.ts',
    pkg: 'desktop',
    desc: 'the main/preload/renderer contract behind `window.ved`',
  },
] as const;

// The OXC extraction follows every re-export, including non-TS ones it
// cannot parse (@ved/editor re-exports its stylesheet). Such an entry is
// extracted through a SHADOW copy with those lines dropped; the styles
// export just goes undocumented.
const shadowOf = (entry: string): string | null => {
  const source = readFileSync(join(REPO_ROOT, entry), 'utf8');
  const kept = source.split('\n').filter((line) => !/from\s+'[^']+\.(scss|css)'/.test(line));
  if (kept.length === source.split('\n').length) return null;
  const shadow = join(dirname(entry), '.api-docs-entry.ts');
  writeFileSync(join(REPO_ROOT, shadow), kept.join('\n'));
  return shadow;
};

const shadows = new Map(MODULES.map((m) => [m.name, shadowOf(m.entry)]));
let modules: ReturnType<typeof extractDocsFromEntryPoints>;
try {
  modules = extractDocsFromEntryPoints(
    MODULES.map((m) => ({ path: shadows.get(m.name) ?? m.entry, name: m.name })),
    { root: REPO_ROOT },
  );
} finally {
  for (const shadow of shadows.values()) {
    if (shadow) unlinkSync(join(REPO_ROOT, shadow));
  }
}

for (const m of modules) {
  for (const d of m.diagnostics) {
    console.error(`${d.code} ${d.entrypoint} ${d.exportName}: ${d.message}`);
  }
}
if (modules.some((m) => m.diagnostics.length > 0)) process.exit(1);

// generateDocsMarkdown takes entry tags as ordered pairs; extraction hands
// them back as a record. A shadowed module's source link points back at the
// real entry.
const pages = generateDocsMarkdown(
  modules.map((m) => {
    const declared = MODULES.find((d) => d.name === m.name);
    if (!declared) throw new Error(`extraction returned unknown module ${m.name}`);
    return {
      file: m.file,
      description: m.description,
      sourcePath: shadows.get(m.name) ? join(REPO_ROOT, declared.entry) : m.sourcePath,
      examples: m.examples,
      tags: m.tags,
      entries: m.entries.map((e) => ({
        ...e,
        tags: e.tags ? Object.entries(e.tags).map(([tag, value]) => ({ tag, value })) : undefined,
      })),
    };
  }),
  {
    // The generator appends `/blob/main/<file relative to its PACKAGE>`.
    githubUrl: 'https://github.com/toyboot4e/ved',
    pathStrategy: 'typedoc',
    renderStyle: 'markdown',
  },
);

const banner = [
  '<!-- GENERATED by scripts/gen-api-docs.ts — do not edit by hand.',
  '     Run `pnpm run api-docs` (or `just doc`) to refresh. -->',
  '',
].join('\n');

// Patch two ox-content@2.76 rendering quirks:
//   - source links relativize the file path to the nearest package, dropping
//     the monorepo segment (`blob/main/src/…` for a file under `desktop/`) —
//     every page belongs to one module, so its links get that module's
//     package dir back (the root index links no sources);
//   - a negative numeric literal type prints as `literal` (`1 | -1` in the
//     source renders `1 | literal`).
const patch = (path: string, content: string): string => {
  const owner = MODULES.find((m) => path.startsWith(`${m.name}/`));
  let out = owner ? content.replaceAll('/blob/main/src/', `/blob/main/${owner.pkg}/src/`) : content;
  if (path === 'index.md') {
    // The root module list renders bare names; annotate each with its role.
    for (const m of MODULES) {
      out = out.replace(`- [${m.name}](./${m.name}/index.md)`, `- [${m.name}](./${m.name}/index.md) — ${m.desc}`);
    }
  }
  return out.replaceAll('1 | literal', '1 | -1');
};

const files = new Map<string, string>(
  Object.entries(pages).map(([path, content]) => [path, banner + patch(path, content)]),
);

if (process.argv.includes('--check')) {
  const onDisk = existsSync(OUT_DIR)
    ? readdirSync(OUT_DIR, { recursive: true, withFileTypes: true })
        .filter((e) => e.isFile())
        .map((e) => join(e.parentPath.slice(OUT_DIR.length + 1), e.name))
    : [];
  const stale =
    onDisk.length !== files.size ||
    [...files].some(([path, content]) => {
      const p = join(OUT_DIR, path);
      return !existsSync(p) || readFileSync(p, 'utf8') !== content;
    });
  if (stale) {
    console.error('API docs are stale — run `pnpm run api-docs`');
    process.exit(1);
  }
  console.log('API docs are up to date');
} else {
  rmSync(OUT_DIR, { recursive: true, force: true });
  for (const [path, content] of files) {
    mkdirSync(dirname(join(OUT_DIR, path)), { recursive: true });
    writeFileSync(join(OUT_DIR, path), content);
  }
  console.log(`wrote ${files.size} pages for ${modules.length} modules`);
}
